workflows:
  my-workflow:
    jobs:
     - build:
        context:
          - 'Test context'
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: env | sort
orbs:
  ruby: circleci/ruby@1.1.2
version: 2.1
